package model

type Camera struct {
	ID                     int    `json:"id"`
	Name                   string `json:"name"`
	ProductType            string `json:"product_type"`
	SensorType             string `json:"sensor_type"`
	ReleaseDate            string `json:"release_date"`
	Discontinued           string `json:"discontinued"`
	ImageSensorSize        string `json:"image_sensor_size"`
	TotalPixels            string `json:"total_pixels"`
	EffectivePixels        string `json:"effective_pixels"`
	ImageProcessor         string `json:"image_processor"`
	StaticImageFormat      string `json:"static_image_format"`
	StaticImageSize        string `json:"static_image_size"`
	FrameRatio             string `json:"frame_ratio"`
	MovieFormat            string `json:"movie_format"`
	MovieSize              string `json:"movie_size"`
	AudioFormat            string `json:"audio_format"`
	DustRemovalSystem      string `json:"dust_removal_system"`
	LensStructure          string `json:"lens_structure"`
	AsphericalLenses       string `json:"aspherical_lenses"`
	FocalLength            string `json:"focal_length"`
	EqFullFrameFocalLength string `json:"eq_full_frame_focal_length"`
	MaximumAperture        string `json:"maximum_aperture"`
	OpticalZoom            string `json:"optical_zoom"`
	RecentFocusingDistance string `json:"recent_focusing_distance"`
	FocusMode              string `json:"focus_mode"`
	LensMount              string `json:"lens_mount"`
	CompatibleLens         string `json:"compatible_lens"`
	FocusSystemType        string `json:"focus_system_type"`
	Focus                  string `json:"focus"`
	MeteringSystem         string `json:"metering_system"`
	MeteringMode           string `json:"metering_mode"`
	AfAssistLight          string `json:"af_assist_light"`
	ExposureMode           string `json:"exposure_mode"`
	ShootingMode           string `json:"shooting_mode"`
	FilmSimulationMode     string `json:"film_simulation_mode"`
	AdvancedFilter         string `json:"advanced_filter"`
	ShutterType            string `json:"shutter_type"`
	ShutterSpeed           string `json:"shutter_speed"`
	FlashSyncSpeed         string `json:"flash_sync_speed"`
	ExposureCompensation   string `json:"exposure_compensation"`
	IsoSensitivity         string `json:"iso_sensitivity"`
	WhiteBalance           string `json:"white_balance"`
	Timer                  string `json:"timer"`
	ContinuousShot         string `json:"continuous_shot"`
	Viewfinder             string `json:"viewfinder"`
	ViewingRange           string `json:"viewing_range"`
	ViewingMagnification   string `json:"viewing_magnification"`
	DiopterAdjustmentRange string `json:"diopter_adjustment_range"`
	FocusScreen            string `json:"focus_screen"`
	Reflector              string `json:"reflector"`
	DeepDepthPreview       string `json:"deep_depth_preview"`
	LcdType                string `json:"lcd_type"`
	LcdSize                string `json:"lcd_size"`
	LcdPixels              string `json:"lcd_pixels"`
	FieldOfView            string `json:"field_of_view"`
	LcdCharacteristics     string `json:"lcd_characteristics"`
	StorageCard            string `json:"storage_card"`
	DataInterface          string `json:"data_interface"`
	VideoAudioInterface    string `json:"video_audio_interface"`
	WirelessFunction       string `json:"wireless_function"`
	Battery                string `json:"battery"`
	BatteryLife            string `json:"battery_life"`
	Colour                 string `json:"colour"`
	Size                   string `json:"size"`
	Weight                 string `json:"weight"`
	OperatingTemperature   string `json:"operating_temperature"`
	WorkingHumidity        string `json:"working_humidity"`
	Annex                  string `json:"annex"`
}
